name: quarto
channels:
  - conda-forge
  - defaults
dependencies:
  # Python Packages
  - python=3.9.7
  - numpy=1.21.5
  - matplotlib
  - plotly_express
  - jupyter
  - ipykernel
  - black
  - flake8
  - seaborn